"""Evaluate analytically obtained expressions"""
import numpy as np
from scipy.integrate import quad, dblquad, tplquad, quad_vec
from scipy import stats
from scipy import constants
from sdesim.helpers import optimize_quadratic_form, set_bounds, outcome_labels, finite_bound
from sdesim.params import make_nondimensional, length_scale
from numba import njit

from scipy.integrate import solve_ivp, quad
from sdesim.models import rhs_bath_model

@njit(cache=True)
def current_matrix_numba(t, params):
    """Evaluates matrix exponential computed using Wolfram Mathematica at given time.

        Parameters: 
        t: float, time of evaluation
        params: SystemVariables

    returns 4x4 matrix saved in numpy ndarray"""
    tau_b = params.tau_b
    tau_p = params.tau_p

    tau_sum = tau_b + tau_p
    trig_argument = np.sqrt(1 + tau_b / tau_p) / tau_b
    sqrt_tau_p = np.sqrt(tau_p)
    tau_sum_sqrt = np.sqrt(tau_sum)
    tau_sum_three_half = tau_sum_sqrt ** 3
    tau_p_three_half = sqrt_tau_p ** 3
    tau_b_squared = tau_b ** 2
    sqrt_sum_times_tau_p = sqrt_tau_p * tau_sum_sqrt

    matrix = np.empty((4, 4))
    sinh_val = np.sinh(t*trig_argument)
    cosh_val = np.cosh(t*trig_argument)

    matrix[0,0] = (tau_b + t + tau_b*cosh_val + 2* tau_p)/(2*tau_sum)- sinh_val * tau_b * sqrt_tau_p/(2*tau_sum_three_half)
    matrix[0,1] = sqrt_tau_p* tau_b_squared*sinh_val/tau_sum_three_half + tau_p*t/tau_sum
    matrix[0,2] = -(-tau_b + t + tau_b*cosh_val)/(2*tau_sum)+ sinh_val * tau_b * sqrt_tau_p/(2*tau_sum_three_half)
    matrix[0,3] =  tau_b*((t + tau_b - cosh_val*tau_b)/(2*tau_sum) -tau_b*sqrt_tau_p * sinh_val/(2*tau_sum_three_half))

    matrix[1,0] = (1-cosh_val)/(2*tau_sum) + sinh_val/(2*sqrt_sum_times_tau_p)
    matrix[1,1] = (cosh_val*tau_b +tau_p)/tau_sum
    matrix[1,2] = - matrix[1,0]
    matrix[1,3] = -tau_b*0.5*(sinh_val/sqrt_sum_times_tau_p + (cosh_val-1)/tau_sum)

    matrix[2,0] = (0.5*t + tau_p - tau_p* cosh_val)/(tau_sum) + sinh_val*(0.5*tau_b*sqrt_tau_p+ tau_p_three_half)/(tau_sum_three_half)
    matrix[2,1] = tau_p*((t +tau_b* cosh_val - tau_b)/(tau_sum)-tau_b * sqrt_tau_p*sinh_val/tau_sum_three_half)
    matrix[2,2] = -(0.5*t - tau_b - tau_p*cosh_val)/(tau_sum) - sinh_val*(0.5*tau_b*sqrt_tau_p+ tau_p_three_half)/(tau_sum_three_half)
    matrix[2,3] = -sqrt_tau_p* tau_b_squared*sinh_val/(2*tau_sum_three_half) + tau_b*t/(2*tau_sum)

    matrix[3,0] = - np.sinh(0.5*t*trig_argument)**2/tau_sum
    matrix[3,1] = sqrt_tau_p*(- sinh_val/tau_sum_sqrt +(1 -cosh_val)*sqrt_tau_p/tau_sum)
    matrix[3,2] = - matrix[3,0]
    matrix[3,3] = (sinh_val* sqrt_sum_times_tau_p + tau_b*0.5 +cosh_val*(0.5*tau_b+ tau_p))/tau_sum

    return matrix

class SolutionMatrixCreator:
    """
    wrapper storing params for reuse, plus the two/three scalar
    attributes (tau_p, k) other code reuses, delegates entirely to
    current_matrix_numba
    """
    def __init__(self, params):
        self.params = params
        self.tau_b = params.tau_b
        self.tau_p = params.tau_p
        self.k = params.k

    def current_matrix(self, t):
        return current_matrix_numba(t, self.params)

@njit(cache=True)
def current_lambda(current_B, c_vector, params):
    """
    Function to compute the optimal trap focus lambda at time t. 
    Parameters:
    current_B: ndarray as generated by SolutionMatrixCreator.current_matrix
    c_vector: np.array with 4 entries, without lambda_f, as returned by get_cvector
    params: SystemVariables object

    Returns: float, lambda(t)"""
    current_solution = current_B @ c_vector
    optim_lambda = (params.tau_p *current_solution[1] + (params.k+1)* current_solution[0] - current_solution[2])/params.k

    return optim_lambda

def make_optimal_protocol_numba(c_vector, t_protocol_end, lambda_f):
    """
    Build a numba-jitted protocol callable matching the signature expected by
    euler_maruyama_ensemble_bath_model's protocol argument
    parameters is supplied at call by the integrator (the same
    SystemVariables passed to euler_maruyama_ensemble_bath_model), so only
    the protocol-specific values are needed

    Parameters: 
    current_B: ndarray as generated by SolutionMatrixCreator.current_matrix
    c_vector: np.array with 4 entries, without lambda_f, as returned by get_cvector
    t_end_protocol: float

    Return: numba compatible optimal protocol function for integrator
    """
    c_vector = np.asarray(c_vector, dtype=np.float64)

    @njit(cache=True)
    def optimal_protocol(t, parameters):
        if t >= t_protocol_end:
            return lambda_f
        B = current_matrix_numba(t, parameters)
        return current_lambda(B, c_vector, parameters)

    return optimal_protocol

def _expand(row):
    """Pad a  row with a trailing 0 """
    return np.concatenate([row, [0.0]])


def _integrand_matrix(t, B_creator):
    """The matrix D has integral contributions. the integrands of those are build as a 5x5 integrand matrix at once
    parameters:
    t: time of evaluation in the integration process
    B_creator: SolutionMatrixCreator

    Returns: 5x5 ndarray containing integrands for D"""
    B = B_creator.current_matrix(t)
    row2 = _expand(B[1, :])
    row3 = _expand(B[2, :])

    # tau_p * row2 outer row2  -  0.5*(row3 outer row2 + row2 outer row3)
    return (B_creator.tau_p * np.outer(row2, row2) - 0.5 * (np.outer(row3, row2) + np.outer(row2, row3)))


def compute_D(B_creator,t_protocol_end, params):
    """Compute matrix defined such that W=c^TDc (c including lambda_f)

    Parameters:
    t_protocol_end: float
    B_creator: SolutionMatrixCreator
    params: SystemVariables

    Returns: 5x5 ndarray"""

    final_B = B_creator.current_matrix(t_protocol_end)
    final_row0 = _expand(final_B[0, :])          # length-5, last entry padded with 0

    e0 = np.zeros(5); e0[0] = 1.0
    e4 = np.zeros(5); e4[4] = 1.0

    # Vectorized version of the two algebraic (non-integral) terms
    term_k   = params.k / 2 * (np.outer(e4, e4) - np.outer(e4, final_row0) - np.outer(final_row0, e4))
    term_kplus1 = (params.k + 1) / 2 * (np.outer(final_row0, final_row0) - np.outer(e0, e0))

    # Single vectorized integration call
    integral, _ = quad_vec(lambda t: _integrand_matrix(t, B_creator), 0,t_protocol_end)

    D = (term_k + term_kplus1 + integral) * params.kappa / params.k
    return D
 
def compute_c2(c1,c3, D):
    """compute c2 = v* using the explicitly solved optimization using the D Matrix paraphrasing the work.

    parameters:
    c1: mean initial paricle position
    c_3: mean initial bath particle position
    D: ndarray containing the explicit matrix s.t. W= c^T D c

    return:
    scalar optimal initial velocity"""
    res = -((c1 * (D[0,4] * D[1,4] * D[3,3] - D[0,4] * D[1,3] * D[3,4] - D[0,3] * D[1,4] * D[3,4] + D[0,1] * D[3,4]**2 + 
        D[0,3] * D[1,3] * D[4,4] - D[0,1] * D[3,3] * D[4,4]) + 
        c3 * (D[1,4] * D[2,4] * D[3,3] - D[1,4] * D[2,3] * D[3,4] - D[1,3] * D[2,4] * D[3,4] + D[1,2] * D[3,4]**2 + 
        D[1,3] * D[2,3] * D[4,4] - D[1,2] * D[3,3] * D[4,4]))/
        (D[1,4]**2 * D[3,3] - 2 * D[1,3] * D[1,4] * D[3,4] + D[1,3]**2 * D[4,4] + D[1,1] * (D[3,4]**2 - D[3,3] * D[4,4])))
    return res

def compute_c4(c1,c3, D):
    """compute c4 = Lambda* using the explicitly solved optimization using the D Matrix paraphrasing the work.

    parameters:
    c1: mean initial paricle position
    c_3: mean initial bath particle position
    D: ndarray containing the explicit matrix s.t. W= c^T D c

    return:
    scalar optimal Lagrange multiplier"""
    res = (c1 * (D[0,4] * D[1,3] * D[1,4] - D[0,3] * D[1,4]**2 - D[0,4] * D[1,1] * D[3,4] + D[0,1] * D[1,4] * D[3,4] + 
        D[0,3] * D[1,1] * D[4,4] - D[0,1] * D[1,3] * D[4,4]) + 
        c3 * (-D[1,4]**2 * D[2,3] + D[1,3] * D[1,4] * D[2,4] + D[1,2] * D[1,4] * D[3,4] - D[1,1] * D[2,4] * D[3,4] - 
        D[1,2] * D[1,3] * D[4,4] + D[1,1] * D[2,3] * D[4,4]))/(
        D[1,4]**2 * D[3,3] - 2 * D[1,3] * D[1,4] * D[3,4] + D[1,3]**2 * D[4,4] + D[1,1] * (D[3,4]**2 - D[3,3] * D[4,4]))
    return res

def compute_c5(c1,c3,D):
    """compute c5 = lambda_f* using the explicitly solved optimization using the D Matrix paraphrasing the work.

    parameters:
    c1: mean initial paricle position
    c_3: mean initial bath particle position
    D: ndarray containing the explicit matrix s.t. W= c^T D c

    return:
    scalar optimal final trap position c5"""
    res = (c1 * (-D[0,4] * D[1,3]**2 + D[0,3] * D[1,3] * D[1,4] + D[0,4] * D[1,1] * D[3,3] - D[0,1] * D[1,4] * D[3,3] - 
        D[0,3] * D[1,1] * D[3,4] + D[0,1] * D[1,3] * D[3,4]) + 
        c3 * (D[1,3] * D[1,4] * D[2,3] - D[1,3]**2 * D[2,4] - D[1,2] * D[1,4] * D[3,3] + D[1,1] * D[2,4] * D[3,3] + 
        D[1,2] * D[1,3] * D[3,4] - D[1,1] * D[2,3] * D[3,4]))/(
        D[1,4]**2 * D[3,3] - 2 * D[1,3] * D[1,4] * D[3,4] + D[1,3]**2 * D[4,4] + D[1,1] * (D[3,4]**2 - D[3,3] * D[4,4]))
    return res

#Marginalized colloids positional equilibrium distribution
def eq_dist(x, params):
    sigma_squared = params.k_B * params.T/params.kappa
    return 1/np.sqrt(2*np.pi * sigma_squared) * np.exp(-x**2/(2*sigma_squared))

# 
def chi(params, time_between_measurements):
    """computes chi, determining the analytical conditional colloids position, helper functions to compute the conditionalized average position after the second measurement
    
    Parameters:
    params: SystemVariables object
    time_between_measurements: float

    returns: scalar chi at given time of second measurement
    """
    Delta = np.sqrt((params.gamma + params.kappa * params.tau_b + params.gamma_b)**2 - 4 * params.kappa * params.gamma * params.tau_b) #Constant defined in analytical considerations
    return 1/Delta * np.exp(-(params.gamma + params.kappa * params.tau_b + params.gamma_b)/(2 * params.gamma * params.tau_b) * time_between_measurements) * ((params.gamma + params.gamma_b - params.kappa * params.tau_b) * np.sinh(time_between_measurements * Delta/(2 * params.gamma * params.tau_b)) + Delta * np.cosh(time_between_measurements * Delta/(2 * params.gamma * params.tau_b)))

def bath_correlation_C(time_between_measurements, params):
    """Calculate value of time correlation of the clolloids position

    Parameters:
    params: SystemVariables object
    time_between_measurements: float, we compute correlation betweeen times of measurements, holds for general times
    
    return:
    float, <X(0)X_(t_between_measurements)>"""

    return params.k_B * params.T / params.kappa *chi(params, time_between_measurements)

def bath_correlation_C_b(t,params):
    """Calculate value of time correlation of the bath particles position at t with initial clolloid position 

    Parameters:
    params: SystemVariables object
    time_between_measurements: float, we compute correlation betweeen times of measurements, holds for general times
    
    return:
    float, <X(0)X_b(t_between_measurements)>"""
    Delta_b = np.sqrt((params.gamma_b * (params.kappa + params.kappa_b) + params.kappa_b * params.gamma)**2 - 4 * params.kappa * params.kappa_b * params.gamma * params.gamma_b)#Constant defined in analytical considerations
    return params.k_B * params.T/(Delta_b * params.kappa) * np.exp(-(params.gamma_b * (params.kappa + params.kappa_b) + params.kappa_b * params.gamma)/(2 * params.gamma * params.gamma_b) * t) * ((params.gamma * params.kappa_b + (params.kappa + params.kappa_b) * params.gamma_b ) * np.sinh(t * Delta_b / (2 * params.gamma * params.gamma_b)) + Delta_b * np.cosh(t * Delta_b / (2 * params.gamma * params.gamma_b)))

def compute_conditional_xt_dist(X_0,params, time_between_measurements):
    """Compute analytical P(X_t|X_0)

        Parameters:
        X_0: Colloids position at time 0(first measurement)
        params: SystemVariables object
        time_between_measurements: float

        Returns:
        stats.multivariate_normal object
    """
    chi_t = chi(params, time_between_measurements)# evaluate chi at current time
    mean = X_0 *chi_t
    variance = params.k_B * params.T / params.kappa * (1-chi_t ** 2)
    return stats.multivariate_normal([mean], [[variance]])

def compute_conditional_xbt_distribution(X_0, params, time_between_measurements):
    """Compute analytical P(X_b,t|X_0)

        Parameters:
        X_0: Colloids position at time 0(first measurement)
        params: SystemVariables object
        time_between_measurements: float

        Returns:
        stats.multivariate_normal object
    """
    C_b_t = bath_correlation_C_b(time_between_measurements,params)
    mean = params.kappa/(params.k_B * params.T) *X_0 *C_b_t
    variance = params.k_B * params.T * (1/params.kappa + 1/ params.kappa_b) - params.kappa/(params.k_B * params.T) * C_b_t**2
    return stats.multivariate_normal([mean], [[variance]])

def norm_intgrand(X_t,X_0, params,time_between_measurements):
    """compute P(X_t,X_0) as product so we have one integrand function.

    Parameters:
    X_0: Colloids position at time 0(first measurement)
    X_t: Colloids position at time t(second measurement)
    time_between_measurements: float

    Return: float, distribution evaluated"""
    conditional_xt_dist = compute_conditional_xt_dist(X_0, params,time_between_measurements)
    return eq_dist(X_0, params) * conditional_xt_dist.pdf(X_t)

def average_intgrand(x_t,x_0,params,time_between_measurements):
    """compute P(X_t,X_0)*X_t as product so we have one integrand function.

    Parameters:
    X_0: Colloids position at time 0(first measurement)
    X_t: Colloids position at time t(second measurement)
    time_between_measurements: float

    Return: float, distribution evaluated multiplied by X_t"""
    conditional_xt_dist = compute_conditional_xt_dist(x_0, params,time_between_measurements)
    return x_t * eq_dist(x_0, params) * conditional_xt_dist.pdf(x_t)

def compute_c1_analytical(m_0, m_t, params, time_between_measurements,n_outcomes=2):
    """Compute c1(initial colloid position) only from analytically derived distributions. 
    Small scales can lead to numerical problems with dblquad, use nondimensional units.
    to ensure ths, don"t use this function, but rather the _SI wrapper

    Parameters:
    params: SystemVariables object
    m_0: integer value of bined first measurement 
    m_t: integer value of bined second measurement 
    time_between_measurements: float
    n_outcomes : int, optional
        Passed to `set_bounds`; default 2 (binary convention).

    Return:
    float, c1"""

    low_bound_0, up_bound_0 = set_bounds(params, m_0,n_outcomes)
    low_bound_t, up_bound_t = set_bounds(params, m_t,n_outcomes)
    norm_integral = dblquad(norm_intgrand,low_bound_0,up_bound_0, lambda x: low_bound_t, lambda x: up_bound_t, args =(params,time_between_measurements))
    weigthing_integral = dblquad(average_intgrand,low_bound_0,up_bound_0, lambda x: low_bound_t, lambda x: up_bound_t, args =(params,time_between_measurements))

    return weigthing_integral[0]/norm_integral[0] #quad functions return value and error, we want to divide values ->[0]

def get_cvector(c1, c3, D):
    """Compute all c's from c1, c3, D from explicitly solved functions for those parameters

    parameters:
    c1: mean initial paricle position
    c_3: mean initial bath particle position
    D: ndarray containing the explicit matrix s.t. W= c^T D c

    return:
    array of c1 to c4 and scalar lambda_f"""
    c2 = compute_c2(c1,c3, D)
    c4 = compute_c4(c1,c3, D)
    lambda_f = compute_c5(c1,c3, D)
    c_vec =np.array([c1,c2,c3,c4])
    return c_vec, lambda_f

def get_cvector_numeric(c1, c3, D):
    """Compute all c's from c1, c3, D solving for optimized c's numerically

    parameters:
    c1: mean initial paricle position
    c_3: mean initial bath particle position
    D: ndarray containing the explicit matrix s.t. W= c^T D c

    return:
    array of c1 to c4 and scalar lambda_f"""
    c2, c4, lambda_f = optimize_quadratic_form(D, [0, 2], [c1, c3], [1, 3, 4])
    c_vec =np.array([c1,c2,c3,c4])
    return c_vec, lambda_f

def mean_work(D,c_vector,lambda_f):
    """Return mean work of optimal protocol. D is defined such that c^TDc=W"""
    c_vec_5 = np.concatenate((c_vector, np.array([lambda_f])))
    return c_vec_5 @ D @ c_vec_5

    
def compute_work_general_protocol(x0, xb0, lambda_func,t_protocol_end, params, lambda_f =None):
    """
    Convention: lambda(0-) = 0 is the implicit pre-protocol reference;
    lambda_func(0.0) should return lambda(0+), i.e. the value right after
    any initial jump. The jump's work is captured automatically through
    the boundary term - no separate term needed.

    x0, xb0     : mean values of X, X_b at t=0
    lambda_func : callable, lambda_func(t) -> float, defined on [0,t_protocol_end]
    t_protocol_end: float
    params      : SystemVariables

    Return: Mean work in the execution of the protocoll
    """
    def rhs_augmented(t, state):
        x, xb, _w = state
        dx_dt, dxb_dt = rhs_bath_model(np.array([x, xb]), lambda_func(t), params)
        dw_dt = lambda_func(t) * dx_dt
        return [dx_dt, dxb_dt, dw_dt]

    initial_step = t_protocol_end / 1000   # same scale as max_step, always well inside bounds
    sol = solve_ivp(rhs_augmented, [0,t_protocol_end], [x0, xb0, 0.0],
                     rtol=1e-10, atol=1e-13, max_step=t_protocol_end / 1000, first_step=initial_step)

    x_tf, integral = sol.y[0, -1], sol.y[2, -1]
    lam_f = lambda_func(t_protocol_end) if lambda_f is None else lambda_f
    boundary = lam_f**2 / 2 - lam_f * x_tf

    return params.kappa * (boundary + integral)

def negative_trap_potential(params, x_squared):
    """Return mean potential energy particle with average squared position x_squared for trap positioned at 0"""
    return - 0.5 * params.kappa * x_squared

def average_xbt_intgrand_direct(x_t, x_0, params, time_between_measurements):
    """
    Integrand for the numerator of c3 = <X_bt | m_0, m_t>, with the X_bt
    integral collapsed analytically via the direct-route Gaussian
    conditional-expectation identity:

        E[X_bt | X_0, X_t] = a_0 * X_0 + a_t * X_t

    where a_0, a_t are obtained by conditioning the joint Gaussian
    (X_0, X_t, X_bt) on (X_0, X_t) directly (rather than sequentially on
    X_0 then X_t) - see the accompanying derivation for the closed-form
    expressions for a_0, a_t in terms of chi(t) and bath_correlation_C_b(t).

    Assumes the equilibrium/pre-protocol means are all zero (consistent
    with `analytical_distribution_eq`), and units chosen such that the
    equilibrium standard deviation of X_0 is O(1) (e.g. k_B = T = kappa = 1),
    so that no finite-bound truncation of the outer integration domain is
    needed.

    Parameters
    ----------
    x_t : float
        Integration variable for X_t.
    x_0 : float
        Integration variable for X_0.
    params : SystemVariables
    time_between_measurements : float
        Time elapsed between the two measurements (t in X_t, X_bt).

    Returns
    -------
    float
        Value of eq_dist(x_0) * P(x_t | x_0) * E[X_bt | x_0, x_t].
    """
    sigma_sq = params.k_B * params.T / params.kappa
    chi_t = chi(params, time_between_measurements)
    C_b_t = bath_correlation_C_b(time_between_measurements, params)
    denom = sigma_sq * (1 - chi_t**2)

    a_0 = (C_b_t - sigma_sq * chi_t) / denom
    a_t = (sigma_sq - C_b_t * chi_t) / denom

    conditional_xt_dist = compute_conditional_xt_dist(x_0, params, time_between_measurements)
    mean_xbt_given_xt_x0 = a_0 * x_0 + a_t * x_t

    return eq_dist(x_0, params) * conditional_xt_dist.pdf(x_t) * mean_xbt_given_xt_x0


def compute_c3_analytical(m_0, m_t, params, time_between_measurements,n_outcomes=2):
    """
    Analytical closed-form computation of c3 = E[X_bt | m_0, m_t].

    Assumes units in which the equilibrium standard deviation of X_0 is
    O(1) (e.g. k_B = T = kappa = 1), so integration bounds of +/- inf can
    be passed directly to dblquad without errors. To ensure this, use 
    compute_c3_analytical_SI wrapper, not this function

    Parameters
    ----------
    m_0, m_t : int
        Measurement outcome labels (0/1 in the binary convention used by
        `set_bounds`).
    params : SystemVariables
    time_between_measurements : float
        Time elapsed between the two measurements.
    n_outcomes : int, optional
        Passed to `set_bounds`; default 2 (binary convention).

    Returns
    -------
    float
        c3 = E[X_bt | m_0, m_t].
    """
    low_bound_0, up_bound_0 = set_bounds(params, m_0,n_outcomes)
    low_bound_t, up_bound_t = set_bounds(params, m_t,n_outcomes)

    norm_integral = dblquad(
        norm_intgrand, low_bound_0, up_bound_0,
        lambda x: low_bound_t, lambda x: up_bound_t,
        args=(params, time_between_measurements),
    )
    weighting_integral = dblquad(
        average_xbt_intgrand_direct, low_bound_0, up_bound_0,
        lambda x: low_bound_t, lambda x: up_bound_t,
        args=(params, time_between_measurements),
    )

    return weighting_integral[0] / norm_integral[0]


def compute_c1_analytical_SI(m_0, m_t, params, time_between_measurements,n_outcomes=2):
    """
    SI-unit wrapper around compute_c1_analytical.

    Internally converts `params to a nondimensional counterpart
    (k_B = T = kappa = 1) via `make_nondimensional`, so the underlying
    dblquad integration operates on an O(1)-scale domain - this avoids the
    numerical fragility of scipy.integrate.quad's infinite-bound transform
    when the equilibrium length scale sqrt(k_B*T/kappa) is far from O(1)

    The nondimensional result is converted back to the length units of the
    original `params` before being returned, so this function is a drop-in,
    unit-correct replacement for compute_c1_analytical: callers never need
    to construct or know about a nondimensional parameter set themselves.

    Parameters
    ----------
    m_0, m_t : int
        Measurement outcome labels (0/1 in the binary convention).
    params : SystemVariables
        Parameter set in the caller's preferred units (e.g. SI).
    time_between_measurements : float
    n_outcomes : int, optional
        Passed to `set_bounds`; default 2 (binary convention).

    Returns
    -------
    float
        c1 = E[X_t | m_0, m_t], in the same length units as `params`.
    """
    params_nondim = make_nondimensional(params)
    c1_nondim = compute_c1_analytical(m_0, m_t, params_nondim, time_between_measurements,n_outcomes)
    return c1_nondim * length_scale(params)


def compute_c3_analytical_SI(m_0, m_t, params, time_between_measurements,n_outcomes=2):
    """
    SI-unit wrapper around compute_c3_analytical. See
    compute_c1_analytical_SI for the rationale and unit-conversion details;
    the same nondimensionalize-integrate-rescale pattern is applied here.

    Parameters
    ----------
    m_0, m_t : int
        Measurement outcome labels (0/1 in the binary convention).
    params : SystemVariables
        Parameter set in the caller's preferred units (e.g. SI).
    time_between_measurements : float
    n_outcomes : int, optional
        Passed to `set_bounds`; default 2 (binary convention).

    Returns
    -------
    float
        c3 = E[X_bt | m_0, m_t], in the same length units as `params`.
    """
    params_nondim = make_nondimensional(params)
    c3_nondim = compute_c3_analytical(m_0, m_t, params_nondim, time_between_measurements,n_outcomes)
    return c3_nondim * length_scale(params)

def _compute_conditional_quantities_analytical(m_0, m_t, params_nondim, time_between_measurements,
                                                  n_outcomes=2, n_sigma=None, epsabs=None, epsrel=None):
    """
    Compute P(m_0, m_t), c1, c3, and E[X_t^2 | m_0, m_t] .

    All four quantities share one nested
    quad_vec pass instead of 4 independent dblquad calls. 

    Parameters:
    m_0, m_t : int
    params_nondim : SystemVariables
        Must already be nondimensional (k_B = T = kappa = 1).
    time_between_measurements : float
    n_outcomes : int, optional
        Default 2.
    n_sigma : float or None, optional
        Default None to use the true (possibly infinite) bounds.
    epsabs, epsrel : float or None, optional
        Default None for both to use scipy's own defaults

    Return:
    probability, c1_nondim, c3_nondim, second_moment_nondim : float
    """
    chi_t = chi(params_nondim, time_between_measurements)
    var_t = 1.0 - chi_t**2  # Var(X_t | X_0), nondimensional (Var(X_0) = 1)

    C_b_t = bath_correlation_C_b(time_between_measurements, params_nondim)
    denom = 1.0 - chi_t**2  # sigma_sq = 1 nondimensionally
    a_0 = (C_b_t - chi_t) / denom
    a_t = (1.0 - C_b_t * chi_t) / denom

    low_bound_0, up_bound_0 = set_bounds(params_nondim, m_0, n_outcomes)
    low_bound_t, up_bound_t = set_bounds(params_nondim, m_t, n_outcomes)
    if n_sigma is not None:
        low_bound_0 = finite_bound(low_bound_0, 0.0, 1.0, n_sigma)
        up_bound_0 = finite_bound(up_bound_0, 0.0, 1.0, n_sigma)
        low_bound_t = finite_bound(low_bound_t, 0.0, 1.0, n_sigma)
        up_bound_t = finite_bound(up_bound_t, 0.0, 1.0, n_sigma)

    tolerance_kwargs = {}
    if epsabs is not None:
        tolerance_kwargs["epsabs"] = epsabs
    if epsrel is not None:
        tolerance_kwargs["epsrel"] = epsrel

    def inner(x_0):
        def integrand_t(x_t):
            pdf_xt_given_x0 = np.exp(-(x_t - chi_t * x_0)**2 / (2 * var_t)) / np.sqrt(2 * np.pi * var_t)
            return np.array([
                pdf_xt_given_x0,
                pdf_xt_given_x0 * x_t,
                pdf_xt_given_x0 * x_t**2,
                pdf_xt_given_x0 * (a_0 * x_0 + a_t * x_t),
            ])
        value, _ = quad_vec(integrand_t, low_bound_t, up_bound_t, **tolerance_kwargs)
        return value * eq_dist(x_0, params_nondim)

    result, _ = quad_vec(inner, low_bound_0, up_bound_0, **tolerance_kwargs)
    probability, c1_weight, second_moment_weight, c3_weight = result

    return (probability, c1_weight / probability, c3_weight / probability,
            second_moment_weight / probability)

def compute_probability_of_outcome_analytical(m_0, m_t, params, time_between_measurements, n_outcomes=2):
    """
    Analytical (nondimensional) computation of P(m_0, m_t): the probability
    that the first measurement yields outcome m_0 and the second yields
    outcome m_t, obtained by integrating the joint density of (X_0, X_t)
    over the corresponding region.

    This is exactly the normalization integral shared by compute_c1_analytical
    and compute_c3_analytical, exposed here as its own function so it can be
    used as a "counts"-like weight (or validity check) independent of any
    particular conditional mean.

    Note
    ----
    Unlike c1/c3, a probability is dimensionless and therefore identical
    whether computed with SI or nondimensional `params` (given consistent
    relative bounds) - so there is no need for a separate `_SI` wrapper
    that rescales the *result*. A `_SI` wrapper is still provided below
    purely so that the integration itself is always performed in
    nondimensional units (for numerical robustness), regardless of what
    units `params` happens to use.

    Parameters
    ----------
    m_0, m_t : int
    params : SystemVariables
        Should be nondimensional for numerically robust integration.
    time_between_measurements : float
    n_outcomes : int, optional
        Default 2.

    Returns
    -------
    float
        P(m_0, m_t), dimensionless, in [0, 1].
    """
    if np.isclose(time_between_measurements, 0.0):
        if m_0 != m_t:
            return 0.0
        low, up = set_bounds(params, m_0, n_outcomes)
        norm, _, _ = _bin_normalization_and_moments_nondim(low, up, params)
        return norm
    low_bound_0, up_bound_0 = set_bounds(params, m_0, n_outcomes)
    low_bound_t, up_bound_t = set_bounds(params, m_t, n_outcomes)
    norm_integral = dblquad(norm_intgrand, low_bound_0, up_bound_0,
                             lambda x: low_bound_t, lambda x: up_bound_t,
                             args=(params, time_between_measurements))
    return norm_integral[0]


def compute_probability_of_outcome_analytical_SI(m_0, m_t, params, time_between_measurements, n_outcomes=2):
    """
    Wrapper around compute_probability_of_outcome_analytical that always
    integrates using a nondimensionalized copy of `params`, regardless of
    what units `params` itself uses. The result is dimensionless and
    therefore requires no rescaling (see the note in
    compute_probability_of_outcome_analytical).

    Parameters
    ----------
    m_0, m_t : int
    params : SystemVariables
        Parameter set in the caller's preferred units (e.g. SI).
    time_between_measurements : float
    n_outcomes : int, optional
        Default 2.

    Returns
    -------
    float
        P(m_0, m_t), dimensionless.
    """
    params_nondim = make_nondimensional(params)
    return compute_probability_of_outcome_analytical(m_0, m_t, params_nondim, time_between_measurements, n_outcomes)

def second_moment_xt_intgrand(x_t, x_0, params, time_between_measurements):
    """
    Integrand for E[X_t^2 | m_0, m_t]: the analytical counterpart to
    `average_intgrand`, weighting by x_t**2 instead of x_t.

    Parameters
    ----------
    x_t, x_0 : float
        Integration variables.
    params : SystemVariables
    time_between_measurements : float

    Returns
    -------
    float
        x_t**2 * eq_dist(x_0) * P(x_t | x_0).
    """
    conditional_xt_dist = compute_conditional_xt_dist(x_0, params, time_between_measurements)
    return x_t**2 * eq_dist(x_0, params) * conditional_xt_dist.pdf(x_t)


def compute_second_moment_xt_analytical(m_0, m_t, params, time_between_measurements, n_outcomes=2):
    """
    Analytical (nondimensional) computation of E[X_t^2 | m_0, m_t].

    Parameters
    ----------
    m_0, m_t : int
    params : SystemVariables
        Should be nondimensional; see compute_second_moment_xt_analytical_SI
        otherwise.
    time_between_measurements : float
    n_outcomes : int, optional
        Default 2.

    Returns
    -------
    float
        E[X_t^2 | m_0, m_t], in (units of `params`)^2.
    """
    low_bound_0, up_bound_0 = set_bounds(params, m_0, n_outcomes)
    low_bound_t, up_bound_t = set_bounds(params, m_t, n_outcomes)
    norm_integral = dblquad(norm_intgrand, low_bound_0, up_bound_0,
                             lambda x: low_bound_t, lambda x: up_bound_t,
                             args=(params, time_between_measurements))
    second_moment_integral = dblquad(second_moment_xt_intgrand, low_bound_0, up_bound_0,
                                      lambda x: low_bound_t, lambda x: up_bound_t,
                                      args=(params, time_between_measurements))
    return second_moment_integral[0] / norm_integral[0]


def compute_second_moment_xt_analytical_SI(m_0, m_t, params, time_between_measurements, n_outcomes=2):
    """
    SI-unit wrapper around compute_second_moment_xt_analytical. Since this
    quantity has dimension length^2, the nondimensional result is rescaled
    by length_scale(params)**2 (not length_scale(params)).

    Parameters
    ----------
    m_0, m_t : int
    params : SystemVariables
        Parameter set in the caller's preferred units (e.g. SI).
    time_between_measurements : float
    n_outcomes : int, optional
        Default 2.

    Returns
    -------
    float
        E[X_t^2 | m_0, m_t], in (units of `params`)^2.
    """
    params_nondim = make_nondimensional(params)
    second_moment_nondim = compute_second_moment_xt_analytical(
        m_0, m_t, params_nondim, time_between_measurements, n_outcomes
    )
    return second_moment_nondim * length_scale(params) ** 2

def _bin_normalization_and_moments_nondim(low, up, params_nondim, n_sigma=None, epsabs=None, epsrel=None):
    """
    Compute the equilibrium probability mass, first moment, and second
    moment of X_0 restricted to [low, up], in a single combined
    quad_vec pass 

    Parameters:
    low, up : float
        Integration bounds (may be +/- np.inf).
    params_nondim : SystemVariables
        Must be nondimensional.
    n_sigma : float or None, optional
        Truncation width for infinite bounds, in standard deviations.
        Default None to
        integrate over the true (possibly infinite) bounds
    epsabs, epsrel : float or None, optional
        Passed to `quad_vec`. Default None for both to fall back to scipy's own
        defaults.

    Returns:
    norm, first_moment, second_moment : float
        Unnormalized integrals of eq_dist, x*eq_dist, x**2*eq_dist over
        [low, up] - divide by norm for conditional moments.
    """
    if n_sigma is not None:
        low = finite_bound(low, 0.0, 1.0, n_sigma)
        up = finite_bound(up, 0.0, 1.0, n_sigma)

    tolerance_kwargs = {}
    if epsabs is not None:
        tolerance_kwargs["epsabs"] = epsabs
    if epsrel is not None:
        tolerance_kwargs["epsrel"] = epsrel

    def integrand(x):
        density = eq_dist(x, params_nondim)
        return np.array([density, density * x, density * x**2])

    values, _ = quad_vec(integrand, low, up, **tolerance_kwargs)
    return values[0], values[1], values[2]

def mean_initial_positions_from_analytical(params, time_between_measurements, n_outcomes=2,
                                            probability_threshold=1e-10, fast=False):
    """
    compute each quantity directly from the closed-form model via
    compute_c1_analytical_SI / compute_c3_analytical_SI /
    compute_second_moment_xt_analytical_SI / compute_probability_of_outcome_analytical_SI.

    Returns the same dict shape (one entry per "m_0=...,m_t=..." key, each
    holding "mean_X_t", "mean_X_bt", "mean_X_t_squared", "counts"), so it
    is a drop-in replacement anywhere mean_initial_positions_from_trajectories
    is used (e.g. as input to process_combination).

    time_between_measurements = 0 is handled as a special case: at that
    limit, X_t = X_0 exactly, so P(X_t | X_0) degenerates to a Dirac delta
    Additionally, for this bath model,
    E[X_bt | X_0] = X_0 exactly at time_between_measurements = 0 (since
    Cov(X_0, X_b0) = Var(X_0) at equilibrium), so mean_X_bt is set equal to
    mean_X_t without a separate integral.

    Parameters:
    params : SystemVariables
    time_between_measurements : float
        Time elapsed between the two measurements.
    n_outcomes : int, optional
        Number of outcome categories per measurement; default 2 .
    probability_threshold : float, optional
        Outcome combinations with P(m_0, m_t) below this threshold are
        treated as having negligible/no probability mass, and their
        conditional means are reported as NaN. Default
        1e-10.
    fast: bool, whether to be less precise and faster( integration bound truncation, justified for Gaussians), default: False


    Returns:
    dict
        Keys "m_0={m_0},m_t={m_t}" for every combination of outcome labels
        (see `outcome_labels`), each mapping to a dict with keys
        "mean_X_t", "mean_X_bt", "mean_X_t_squared", "counts" (always None).
    
    """
    n_sigma = 8 if fast else None
    epsabs = 1e-6 if fast else None
    epsrel = 1e-6 if fast else None
    labels = outcome_labels(n_outcomes)
    results = {}

    if np.isclose(time_between_measurements, 0.0):
        params_nondim = make_nondimensional(params)
        L0 = length_scale(params)

        for m_0 in labels:
            for m_t in labels:
                key = f"m_0={m_0},m_t={m_t}"

                if m_0 != m_t:
                    results[key] = {
                        "mean_X_t": np.nan, "mean_X_bt": np.nan,
                        "mean_X_t_squared": np.nan, "counts": None,
                    }
                    continue

                low, up = set_bounds(params_nondim, m_0, n_outcomes)
                norm, first_moment, second_moment = _bin_normalization_and_moments_nondim(
                    low, up, params_nondim, n_sigma=n_sigma, epsabs=epsabs, epsrel=epsrel
                )

                if norm < probability_threshold:
                    results[key] = {
                        "mean_X_t": np.nan, "mean_X_bt": np.nan,
                        "mean_X_t_squared": np.nan, "counts": None,
                    }
                    continue

                mean_X_t_nondim = first_moment / norm
                mean_X_t_squared_nondim = second_moment / norm
                mean_X_bt_nondim = mean_X_t_nondim

                results[key] = {
                    "mean_X_t": mean_X_t_nondim * L0,
                    "mean_X_bt": mean_X_bt_nondim * L0,
                    "mean_X_t_squared": mean_X_t_squared_nondim * L0**2,
                    "counts": None,
                    "probability": norm,
                }

        return results

    #mean initial conditions are computed in non dimensionalized units because numerical integration is more stable 
    #for O(1), then rescaled
    params_nondim = make_nondimensional(params)
    L0 = length_scale(params)

    for m_0 in labels:
        for m_t in labels:
            key = f"m_0={m_0},m_t={m_t}"
            probability, c1_nondim, c3_nondim, second_moment_nondim = (
                _compute_conditional_quantities_analytical(
                    m_0, m_t, params_nondim, time_between_measurements, n_outcomes,
                    n_sigma=n_sigma, epsabs=epsabs, epsrel=epsrel,
                )
            )

            if probability < probability_threshold:
                results[key] = {
                    "mean_X_t": np.nan, "mean_X_bt": np.nan,
                    "mean_X_t_squared": np.nan, "counts": None, "probability": probability,
                }
                continue

            results[key] = {
                "mean_X_t": c1_nondim * L0,
                "mean_X_bt": c3_nondim * L0,
                "mean_X_t_squared": second_moment_nondim * L0**2,
                "counts": None,
                "probability": probability,
            }

    return results

def mean_second_measurement_positions_from_analytical(params, n_outcomes=2, probability_threshold=1e-10,fast=False):
    """
    Mean colloid position conditioned only on a single measurement outcome
    m_t, as if no earlier measurement had ever been taken.

    Parameters:
    params : SystemVariables
    n_outcomes : int, optional
        Default 2.
    probability_threshold : float, optional
        m_t outcomes with marginal probability below this are reported as
        NaN. Default 1e-10.
    fast: bool, whether to be less precise and faster, default: False

    Returns:
    dict
        Keys "m_t={m_t}", each mapping to a dict with "mean_X_t" (in the
        units of `params`) and "probability" (dimensionless, the
        equilibrium marginal P(m_t)).
    """
    n_sigma = 8 if fast else None
    epsabs = 1e-6 if fast else None
    epsrel = 1e-6 if fast else None
    params_nondim = make_nondimensional(params)
    L0 = length_scale(params)
    labels = outcome_labels(n_outcomes)

    results = {}
    for m_t in labels:
        low, up = set_bounds(params_nondim, m_t, n_outcomes)
        norm, first_moment, _ = _bin_normalization_and_moments_nondim(
            low, up, params_nondim, n_sigma=n_sigma, epsabs=epsabs, epsrel=epsrel
        )
        if norm < probability_threshold:
            results[f"m_t={m_t}"] = {"mean_X_t": np.nan, "probability": 0.0}
        else:
            results[f"m_t={m_t}"] = {"mean_X_t": (first_moment / norm) * L0, "probability": norm}
    return results